- hosts: kube-master
  tasks:
  - name: Copy audit-pod-policy.yaml to /etc/kubernetes
    copy:
      src: /home/ubuntu/rbac/audit-policy-pod.yaml
      dest: /etc/kubernetes/audit-policy-pod.yaml
      owner: root
      group: root

  - name: Add audit parameters to kube-apiserver.yaml
    blockinfile:
      path: /etc/kubernetes/manifests/kube-apiserver.yaml
      block: |2
            - --audit-log-path=-
            - --audit-policy-file=/etc/kubernetes/audit-policy.yaml
      marker: "# {mark} Adding audit-log params"
      insertafter: "- kube-apiserver"

  - name: Add volumeMount parameters to kube-apiserver.yaml
    blockinfile:
      path: /etc/kubernetes/manifests/kube-apiserver.yaml
      block: |2
            - mountPath: /etc/kubernetes/audit-policy.yaml
              name: audit-policy
              readOnly: true
      marker: "# {mark} Adding mountPath params"
      insertafter: "volumeMounts:"

  - name: Add volumes parameters to kube-apiserver.yaml
    blockinfile:
      path: /etc/kubernetes/manifests/kube-apiserver.yaml
      block: |2
          - hostPath:
              path: /etc/kubernetes/audit-policy-pod.yaml
              type: File
            name: audit-policy
      marker: "# {mark} Adding hostPath params"
      insertafter: "volumes:"
