apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  labels:
    app: ghost
    track: production
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ghost
    track: production
