apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
spec:
  limits:
  - default:
      cpu: .5
      memory: 512Mi
    defaultRequest:
      cpu: 0.2
      memory: 200Mi
    type: Container
  - type: PersistentVolumeClaim
    max:
      storage: 1Gi
    min:
      storage: 100Mi
