apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: "5"
    persistentvolumeclaims: "4"
    pods: "10"
    secrets: "10"
    services: "10"
    services.nodeports: "2"
